#ifndef NN_PROGRAM_H
#define NN_PROGRAM_H

#include <autoc/nn/evaluator.h>
#include <autoc/eval/sensor_math.h>
#include <autoc/eval/cone_constants.h>

// Generated NN evaluator function
// This function is generated by nn2cpp and implemented in nn_program_generated.cpp
gp_scalar generatedNNProgram(PathProvider& pathProvider, AircraftState& aircraftState, gp_scalar arg);

// Zero the recurrent hidden state (nn_reset). Call at engage/span start —
// the first tick after this is the warm-up tick (recurrent_reset marker).
void generatedNNProgramReset();

// 039 D5 — arena geometry TEMPLATE baked at codegen time (nn2cpp -a R,F,C).
// Placement is engage-scoped: msplink resolves the active arena from this
// template + the engage point (autoc::eval::resolveEngageArena).
const autoc::eval::FlightArena& generatedNNProgramArenaTemplate();

// 041 P5-3 — tracking-cone constants baked at codegen time (nn2cpp -c ...).
// SCORE_GRAD_* is an exact closed form over the virtual target's geometry, and
// it is only the RIGHT gradient against the cone the objective was shaped with.
const autoc::eval::ConeConstants& generatedNNProgramConeConstants();

// Engage-scoped ACTIVE arena consumed by the generated gather call.
// DEFINED in msplink.cpp (returns the span's resolved virtual-frame arena);
// the generated code only declares it — a missing definition fails the link.
const autoc::eval::FlightArena& nnActiveArena();

// NN program source identifier (weight file path or S3 key) for logging
extern const char* generatedNNProgramSource;

// 039 — identity constants baked by nn2cpp (boot banner + flight-log
// FileHeader provenance): first 8 bytes of SHA-256 of the weight file and
// of the generated code text (see the generated identity trailer).
extern const uint8_t generatedNNWeightId[8];
extern const uint8_t generatedNNFirmwareId[8];
extern const char* generatedNNTopologyString;
extern const int generatedNNInputCount;
extern const int generatedNNWeightCount;

#endif
